overrides:
  lodash@<4.17.11: '>=4.17.11'
  underscore.string@<3.3.5: '>=3.3.5'
  got@<11.8.5: '>=11.8.5'
  lodash@<4.17.21: '>=4.17.21'
  minimist@<0.2.1: '>=0.2.1'
  lodash@<4.17.5: '>=4.17.5'
  lodash@<4.17.12: '>=4.17.12'
  minimist@<0.2.4: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'
  ip@<1.1.9: '>=1.1.9'
  http-cache-semantics@<4.1.1: '>=4.1.1'
  cross-spawn@<6.0.6: '>=6.0.6'
